services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - shahd_network


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: myapp_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - shahd_network


  admin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - shahd_network


networks:
  shahd_network:

volumes:
  db_data:
